### PR TITLE
Improve setup instructions.

### PR DESCRIPTION
**Pull request by cleverer**
I spent like 2 hours not getting the seeding to work…

### CODE REVIEW

**Comment by Michael-Schaer** [comment]
@Cleverer: I also copied the file manually. But then again the script seems to have this covered. Not sure why this doesn't work...

https://github.com/nxt-engineering/hitobito-docker/blob/5d6f00f262584fd224187ed5765c83edf87bc12b/Dockerfile#L9

**Comment by cleverer** [comment]
> @cleverer: I also copied the file manually. But then again the script seems to have this covered. Not sure why this doesn't work...
> 
> https://github.com/nxt-engineering/hitobito-docker/blob/5d6f00f262584fd224187ed5765c83edf87bc12b/Dockerfile#L9

This only happens on building the Docker image. As we mount the directory [in the docker-compose file](https://github.com/nxt-engineering/hitobito-docker/blob/5d6f00f262584fd224187ed5765c83edf87bc12b/docker-compose.yml#L15), that file gets overlaid by the real filesystem and isn't available anymore.

**Comment by carlobeltrame** [comment]
I'd prefer to automate as much as possible when using this repository. Please consider my alternative solution #5

**Comment by cleverer** [comment]
I like your solution! However I think we still should mention it somewhere, as it is possible to skip the entrypoint (e.g. when using a IDE integration). But maybe we should put it in the Internals section or add a new Troubleshooting-section. This would probably be good in any case.

**Review by cimnine — APPROVED** [review]

**Pull request merged**
